### ISSUE TITLE
Transkribus auth backend: map isAdmin to is_staff rather than is_superuser in Django

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-utils#4]
copied from Transkribus/TranskribusWebUI#9 by @bejohu

In [read.backends.TranskribusBackend](https://github.com/Transkribus/TranskribusWebUI/blob/master/read/backends.py) upon user creation _isAdmin_ attribute from Transkribus server is mapped to Django's _User.is_superuser_ thereby granting [excessive privileges](https://docs.djangoproject.com/en/1.10/ref/contrib/auth/#django.contrib.auth.models.User.is_superuser), while _is_staff_ attribute represents more restricted, yet equally adequate mapping.

**Comment by cziaarm** [comment]
done this

**Comment by cziaarm** [comment]
@maxbry not sure ho to test this may be easier to look at the code

**Comment by maxbry** [comment]
@cziaarm Have the changes been made to this repository? From last month's commits I couldn't find something referring to that.
