### ISSUE TITLE
Stop sending HttpResponseRedirect from TranskribusSession.request on failure

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-utils#5]
If a t.request fails a redirect is returned. While this can be handy for when a view want to respond to a t.request fail by redirecting to logout, this may not be what the view wants to do in everycase (eg a view called via ajax). Much better that the reponse from Trankribus  (error code, status, etc) is passed back to the view and the view can decide the next step.

**Comment by cziaarm** [comment]
implemented with an error handler that wil render an error message page or pass the user back to the log in page with a suitable message if the transkribus request is met with a 401

**Comment by maxbry** [comment]
Referring to [this commit](https://github.com/Transkribus/TWI-utils/commit/050fd8523a152eb6e00d60161b543d5700dd39df#diff-04d2c9518498da64bfa9db44c6211645R6): Is importing something as `_` considered good style?
